version: '3'
services:
  psibase:
    image: ghcr.io/gofractally/psibase-contributor:073ffc7576039990f47c4389c1258b5033190d60
    ports:
      - 8080:8080
    container_name: psibase-contributor
    env_file:
      - path: .env
        required: false
    environment:
      - VITE_SECURE_LOCAL_DEV=true
      - VITE_SECURE_PATH_TO_CERTS=/root/certs/
      # Manually update this whenever changes are made
      - PSIBASE_CONTRIBUTOR_VERSION=0.13
    volumes:
      - type: volume
        source: psibase-contributor
        target: /root/psibase
      - type: bind
        source: ../local-certs
        target: /root/certs
    command: sleep infinity
  mkcert:
    image: vishnunair/docker-mkcert:latest
    container_name: mkcert
    command: [ "/bin/sh", "-c", "mkcert -install && mkcert psibase.127.0.0.1.sslip.io '*.psibase.127.0.0.1.sslip.io' && cp /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem.crt && tail -f -n0 /etc/hosts" ]
    volumes:
      - type: bind
        source: ../local-certs
        target: /root/.local/share/mkcert

volumes:
  psibase-contributor:

    # Original from gh
    #command: "mkcert -install && for i in $(echo $domain | sed "s/,/ /g"); do mkcert $i; done && tail -f -n0 /etc/hosts"
