version: '3'
services:
  psibase-test:
    build: .
    container_name: psibase-contributor-test
    ports:
      - 8080:8080
    environment:
      - VITE_SECURE_LOCAL_DEV=true
      - VITE_SECURE_PATH_TO_CERTS=/root/certs/
    volumes:
      - type: volume
        source: psibase-contributor-test
        target: /root/psibase
      - type: bind
        source: ../artifacts
        target: /root/psibase/rust/psibase/boot-image
      - type: bind
        source: ../local-certs
        target: /root/certs
    command: sleep infinity


volumes:
  psibase-contributor-test:


# Original from gh
#command: "mkcert -install && for i in $(echo $domain | sed "s/,/ /g"); do mkcert $i; done && tail -f -n0 /etc/hosts"
