services:
  psibase:
    image: ghcr.io/gofractally/psibase-contributor:c38d79e2f477c34387ccd824c3e33797691eccb4
    ports:
      - "8070-8090:8070-8090"
    container_name: psibase-contributor
    env_file:
      - path: .env
        required: false
    environment:
      - VITE_SECURE_LOCAL_DEV=true
      - VITE_SECURE_PATH_TO_CERTS=/root/certs/
      # Manually update this whenever changes are made
      - PSIBASE_CONTRIBUTOR_VERSION=0.15
    volumes:
      - type: volume
        source: psibase-contributor
        target: /root/psibase
      - type: bind
        source: ../local-certs
        target: /root/certs
      - type: volume
        source: psibase-contributor-cursor
        target: /root/.cursor
    command: sleep infinity
  mkcert:
    image: vishnunair/docker-mkcert:latest
    container_name: mkcert
    command: [ "/bin/sh", "-c", "mkcert -install && mkcert psibase.127.0.0.1.sslip.io '*.psibase.127.0.0.1.sslip.io' && cp /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem.crt && tail -f -n0 /etc/hosts" ]
    volumes:
      - type: bind
        source: ../local-certs
        target: /root/.local/share/mkcert

volumes:
  psibase-contributor:
  psibase-contributor-cursor:

    # Original from gh
    #command: "mkcert -install && for i in $(echo $domain | sed "s/,/ /g"); do mkcert $i; done && tail -f -n0 /etc/hosts"
