services:
  psibase:
    image: ghcr.io/gofractally/psibase-contributor:983d7b62457785036f381163a2e50039f304e517
    ports:
      - "8070-8090:8070-8090"
    container_name: psibase-contributor
    env_file:
      - path: .env
        required: false
    environment:
      - AGENT_CONFIG_REPO_URL=
      - GH_TOKEN=
      # Manually update this whenever changes are made
      - PSIBASE_CONTRIBUTOR_VERSION=0.18
    volumes:
      - type: volume
        source: psibase-contributor
        target: /root/psibase
      - type: bind
        source: ./init-agent-config.sh
        target: /root/init-agent-config.sh
        read_only: true
      - type: volume
        source: psibase-contributor-cursor
        target: /root/.cursor
    command: sleep infinity

volumes:
  psibase-contributor:
  psibase-contributor-cursor:
